import pprint

from app.billing import BillingManager
from app.cart import CartManager
from app.categories import CategoryManager
from app.product import ProductManager


def my_cart(choice):
    switcher = {
        1: lambda: CategoryManager().add_product_category(),
        2: lambda: ProductManager().add_new_product(),
        3: lambda: CartManager().get_product_from_cart(),
        4: lambda: BillingManager().get_all_bills(),
    }
    return switcher.get(choice, lambda: 'Invalid')()


if __name__ == '__main__':
    while True:
        print('\nMyCart E-commerce app')
        print('\n1. Add product category')
        print('2. Add product')
        print("3. Display user cart details")
        print('4. Display all bills generated by user')

        choice = int(input('Enter your choice: '))
        data = my_cart(choice)
        print('\n')
        pprint.pprint(data)

